-- 1. Profiles Table
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
  github_pat TEXT,
  gemini_api_key TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own profile" ON public.profiles
  FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Users can update own profile" ON public.profiles
  FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Users can insert own profile" ON public.profiles
  FOR INSERT WITH CHECK (auth.uid() = id);

-- 2. User Repositories Table
CREATE TABLE IF NOT EXISTS public.user_repositories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  github_repo_id BIGINT NOT NULL, -- The internal GitHub ID
  owner TEXT NOT NULL,
  name TEXT NOT NULL,
  full_name TEXT NOT NULL,
  description TEXT,
  language TEXT,
  stargazers_count INTEGER,
  avatar_url TEXT,
  default_branch TEXT NOT NULL,
  is_current BOOLEAN DEFAULT false, -- To track which repo the user was last working on
  last_synced_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
 
  -- Ensure a user doesn't save the same repo twice
  UNIQUE(user_id, github_repo_id)
);

ALTER TABLE public.user_repositories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own repositories" ON public.user_repositories
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own repositories" ON public.user_repositories
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own repositories" ON public.user_repositories
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own repositories" ON public.user_repositories
  FOR DELETE USING (auth.uid() = user_id);

-- 3. Auth Trigger for Profiles
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id)
  VALUES (new.id);
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Sync existing users if any
INSERT INTO public.profiles (id)
SELECT id FROM auth.users
ON CONFLICT (id) DO NOTHING;

-- 4. Issue Analyses Table
CREATE TABLE IF NOT EXISTS public.issue_analyses (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  repo_owner TEXT NOT NULL,
  repo_name TEXT NOT NULL,
  issue_number INTEGER NOT NULL,
  analysis TEXT,
  suggested_fix TEXT,
  needs_info BOOLEAN DEFAULT false,
  ai_proposal JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,

  -- Unique constraint to ensure one analysis per issue per repo
  UNIQUE(repo_owner, repo_name, issue_number)
);

ALTER TABLE public.issue_analyses ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can view analyses" ON public.issue_analyses
  FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can insert analyses" ON public.issue_analyses
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can update analyses" ON public.issue_analyses
  FOR UPDATE USING (auth.role() = 'authenticated');

-- 5. PR Analyses Table
CREATE TABLE IF NOT EXISTS public.pr_analyses (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  repo_owner TEXT NOT NULL,
  repo_name TEXT NOT NULL,
  pr_number INTEGER NOT NULL,
  analysis JSONB, -- Stores the review report
  ai_proposal JSONB, -- Stores the suggested fix
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(repo_owner, repo_name, pr_number)
);

ALTER TABLE public.pr_analyses ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can view PR analyses" ON public.pr_analyses 
  FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can insert PR analyses" ON public.pr_analyses 
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can update PR analyses" ON public.pr_analyses 
  FOR UPDATE USING (auth.role() = 'authenticated');

-- 6. CI Analyses Table
CREATE TABLE IF NOT EXISTS public.ci_analyses (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  repo_owner TEXT NOT NULL,
  repo_name TEXT NOT NULL,
  run_id BIGINT NOT NULL,
  analysis TEXT,
  suggested_fix TEXT,
  ai_proposal JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(repo_owner, repo_name, run_id)
);

ALTER TABLE public.ci_analyses ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can view CI analyses" ON public.ci_analyses 
  FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can insert CI analyses" ON public.ci_analyses 
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can update CI analyses" ON public.ci_analyses 
  FOR UPDATE USING (auth.role() = 'authenticated');

-- 7. Repo Documentation Table
CREATE TABLE IF NOT EXISTS public.repo_documentation (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  repo_owner TEXT NOT NULL,
  repo_name TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,

  -- Unique constraint to ensure one documentation entry per repo
  UNIQUE(repo_owner, repo_name)
);

ALTER TABLE public.repo_documentation ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can view docs" ON public.repo_documentation
  FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can insert docs" ON public.repo_documentation
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can update docs" ON public.repo_documentation
  FOR UPDATE USING (auth.role() = 'authenticated');
